name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: lw-config
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly
          target: x86_64-unknown-linux-gnu

      - name: Build tray
        run: >
          rustup component add rust-src --toolchain nightly ;
          cargo build --release ;
          mv -fv target/x86_64-unknown-linux-gnu/release/lw-config ./ ;
          rm -rf target ;

      - name: Build archlinux packages
        uses: countstarlight/arch-makepkg-action@master
        with:
          scripts: makepkg -fsCc --noconfirm --nodeps

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: lw-config-*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
